name: transactions_local
services:
  api_gtw:
    container_name: naty_transfers
    image: naty_transfer_image
    build:
      context: ../
      dockerfile: ./infrastructure/dockerfile
    ports:
      - "3000:3000"
      - "3002:3002" #port for invoking lambda
    volumes:
      - ../src:/app/src
      - ../resources:/app/resources
    env_file:
      - ../.env
    command:
      - ${ARG1}
   
    