FROM node:18.20-slim as node18_base
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
FROM node18_base as dependencies
COPY serverless.yml .
WORKDIR /app
ENTRYPOINT ["npx","serverless"]
